name: Sync to Fork

on:
  push:
    branches: [develop]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 조직 레포
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to fork repo
        run: |
          git config user.name "Heoeunjin"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git remote add fork https://x-access-token:${{ secrets.FORK_DISPATCH_TOKEN }}@github.com/Heoeunjin/KSNET-CDD-Frontend.git
          git push fork develop --force