name: Sync to Deploy Repo

on:
  push:
    branches: [develop]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 조직 레포
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 조직 레포의 기본 권한을 꺼야 내 개인 토큰이 제대로 작동합니다.
          persist-credentials: false

      - name: Push to new repo
        env:
          MY_TOKEN: ${{ secrets.FORK_DISPATCH_TOKEN }}
        run: |
          git config user.name "Heoeunjin"
          git config user.email "${{ secrets.GIT_EMAIL }}"

          git remote remove deploy || true
          

          git remote add deploy https://Heoeunjin:${MY_TOKEN}@github.com/Heoeunjin/KSNET-CDD-Frontend-Deploy.git
          
          git push deploy develop:develop --force