name: Sync to Fork

on:
  push:
    branches: [develop]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 조직 레포
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to fork repo
        env:
          MY_TOKEN: ${{ secrets.FORK_DISPATCH_TOKEN }}
        run: |
          git config user.name "Heoeunjin"
          git config user.email "${{ secrets.GIT_EMAIL }}"

          git remote remove fork || true
          
          git remote add fork https://x-access-token:${MY_TOKEN}@github.com/Heoeunjin/KSNET-CDD-Frontend.git
          
          git push fork develop:develop --force